* Instruções para montar sua apresentação do projeto

* Opção 1: Copiar os arquivos do Manual do Usuário e então apagar o que não entra na apresentação
** Termine de escrever o manual do desenvolvedor
*** Escrever os capítulos
*** Testar a geração do PDF do manual do desenvolvedor
** Depois de finalizada a geração do manual do desenvolvedor, copiar para o diretório Apresentacao todos os arquivos do LyX
*** cd  LDSC-ProjetoEngenharia-2-Software-TituloProjeto-ModeloCompleto/4-Execucao-Detalhamento-Construcao-Versao-1/doc/ManualDoDesenvolvedor/
*** cp * ../Apresentacao/
*** Note que deve copiar os dados da última versão, então esteja atendo para copiar da versão 1-2-3...correta.
*** Você pode economizar memória apagando o diretório Apresentacao/Imagens e trocando o mesmo por um link simbólico.
**** cd Apresentacao/Imagens
**** rm *
**** cd ..
**** ln -s ../ManualDoDesenvolvedor/Imagens
** Abra o arquivo Apresentacao.lyx.
** Gere o PDF.
** Note que vai incluir TODAS as informações que estavam no manual do desenvolvedor.
** O que você tem de fazer é sair apagando aquilo que não é fundamental, deixar apenas os itens necessários a apresentação.

* Opção 2: Construir a apresentação do zero usando o modelo de Apresentação disponibilizado.
** Neste caso você terá de alterar o arquivo Apresentacao.lyx
** Mantenha a mesma estrutura do arquivo do manual do desenvolvedor
"Capa"
"Sumário"
"0-Introducao-Escopo-Objetivos-Metodologia.lyx"
"2-Elaboracao.lyx"
"3-AnaliseOrientadaAObjeto.lyx"
"4-Projeto.lyx"
"5-Ciclos-Planejamento-Detalhamento.lyx"
"6-Ciclos-Construcao-Implementacao.lyx"
"7-Teste.lyx"
"8-DocumentacaoDoDesenvolvedor.lyx"
"bibliografia"
"-Apendice-A.lyx"
